#!/bin/bash

FILES_ALL="*/*.go */*/*.go */Dockerfile */*.sh"
#FILES_CUR="cmd/*.go */*/*.go ./release-builder/main.go"
FILES_CUR="./release-builder/main.go cmd/main.go internal/wiki/wiki.go internal/util/util.go"
#FILES_CUR="cmd/main.go internal/wiki/wiki.go internal/util/util.go"

#FILES="$FILES_ALL"
FILES="$FILES_CUR"

vi -p $FILES
